language: node_js
node_js:
# Versão do node que é utilizada no projeto.
  - 12

# Script que tem que ser executado antes do antes do script "principal"
before_script:
# Pode ser usado npm ou yarn, escolhemos usar yarn.
  - yarn install

# Script "principal"
script:
# Script de teste encontrado no package.json
  - yarn test
# Script dos testes end-to-end
  - yarn run test:e2e

# Caso necessário você pode settar configurações para serem excutadas depois do script "principal" com a configuração # after_script #
